export var nodes =  [
    // { id: "Chorus", total: 60, a1s1: 0, a1s2: 0 },
    { id: "Hermia",       radius: 0, visible: true, total: 1286, a1s1: 432, a1s2: 0,   a2s1: 0,   a2s2: 205},
    { id: "Mote",         radius: 0, visible: true, total: 3,    a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Peaseblossom", radius: 0, visible: true, total: 5,    a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Titania",      radius: 0, visible: true, total: 1082, a1s1: 0,   a1s2: 0,   a2s1: 545, a2s2: 67},
    { id: "Demetrius",    radius: 0, visible: true, total: 1069, a1s1: 13,  a1s2: 0,   a2s1: 190, a2s2: 18},
    { id: "Hippolyta",    radius: 0, visible: true, total: 249,  a1s1: 35,  a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Second fairy", radius: 0, visible: true, total: 10,   a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 10},
    { id: "Quince",       radius: 0, visible: true, total: 864,  a1s1: 0,   a1s2: 337, a2s1: 0,   a2s2: 0},
    { id: "Lysander",     radius: 0, visible: true, total: 1396, a1s1: 406, a1s2: 0,   a2s1: 0,   a2s2: 359},
    { id: "Helena",       radius: 0, visible: true, total: 1815, a1s1: 350, a1s2: 0,   a2s1: 292, a2s2: 256},
    { id: "Puck",         radius: 0, visible: true, total: 1378, a1s1: 0,   a1s2: 0,   a2s1: 273, a2s2: 105},
    { id: "First fairy",  radius: 0, visible: true, total: 44,   a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 44},
    { id: "Theseus",      radius: 0, visible: true, total: 1720, a1s1: 467, a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Cobweb",       radius: 0, visible: true, total: 5,    a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Egeus",        radius: 0, visible: true, total: 290,  a1s1: 213, a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Snout",        radius: 0, visible: true, total: 160,  a1s1: 0,   a1s2: 3,   a2s1: 0,   a2s2: 0}, 
    { id: "Oberon",       radius: 0, visible: true, total: 1609, a1s1: 0,   a1s2: 0,   a2s1: 605, a2s2: 54},
    { id: "Starveling",   radius: 0, visible: true, total: 90,   a1s1: 0,   a1s2: 3,   a2s1: 0,   a2s2: 0 },
    { id: "Flute",        radius: 0, visible: true, total: 356,  a1s1: 0,   a1s2: 21,  a2s1: 0,   a2s2: 0},
    { id: "Philostrate",  radius: 0, visible: true, total: 185,  a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Mustardseed",  radius: 0, visible: true, total: 8,    a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0},
    { id: "Bottom",       radius: 0, visible: true, total: 2035, a1s1: 0,   a1s2: 365, a2s1: 0,   a2s2: 0}, 
    { id: "Snug",         radius: 0, visible: true, total: 120,  a1s1: 0,   a1s2: 20,  a2s1: 0,   a2s2: 0},
    { id: "Fairy",        radius: 0, visible: true, total: 187,  a1s1: 0,   a1s2: 0,   a2s1: 0,   a2s2: 0 }
  ];
  //a5s1 Quince 86


const characters = {
    HERMIA: nodes[0],
    MOTE: nodes[1],
    PEASEBLOSSOM: nodes[2],
    TITANIA: nodes[3],
    DEMETRIUS: nodes[4],
    HIPPOLYTA: nodes[5],
    SECONDFAIRY: nodes[6],
    QUINCE: nodes[7],
    LYSANDER: nodes[8],
    HELENA: nodes[9],
    PUCK: nodes[10],
    //PROLOGUE: nodes[11],
    FIRSTFAIRY: nodes[11],
    THESEUS: nodes[12],
    COBWEB: nodes[13],
    EGEUS: nodes[14],
    SNOUT: nodes[15],
    OBERON: nodes[16],
    STARVELING: nodes[17],
    FLUTE: nodes[18],
    PHILOSTRATE: nodes[19],
    MUSTARDSEED: nodes[20],
    BOTTOM: nodes[21],
    SNUG: nodes[22],
    FAIRY: nodes[23]
}

export const links = [
    { source: characters.HERMIA, target: characters.DEMETRIUS },
    { source: characters.HERMIA, target: characters.LYSANDER },
    { source: characters.HERMIA, target: characters.HELENA },
    { source: characters.HERMIA, target: characters.THESEUS },

    { source: characters.MOTE, target: characters.TITANIA },
    { source: characters.MOTE, target: characters.BOTTOM },

    { source: characters.PEASEBLOSSOM, target: characters.TITANIA },
    { source: characters.PEASEBLOSSOM, target: characters.BOTTOM },

    { source: characters.TITANIA, target: characters.OBERON },
    { source: characters.TITANIA, target: characters.FIRSTFAIRY },
    { source: characters.TITANIA, target: characters.SECONDFAIRY },
    { source: characters.TITANIA, target: characters.BOTTOM },
    { source: characters.TITANIA, target: characters.MOTE },
    { source: characters.TITANIA, target: characters.PEASEBLOSSOM },
    { source: characters.TITANIA, target: characters.COBWEB },
    { source: characters.TITANIA, target: characters.MUSTARDSEED },

    { source: characters.DEMETRIUS, target: characters.HERMIA },
    { source: characters.DEMETRIUS, target: characters.LYSANDER },
    { source: characters.DEMETRIUS, target: characters.HELENA },
    { source: characters.DEMETRIUS, target: characters.THESEUS },
    { source: characters.DEMETRIUS, target: characters.SNUG },

    { source: characters.HIPPOLYTA, target: characters.THESEUS },
    { source: characters.HIPPOLYTA, target: characters.STARVELING },

    { source: characters.SECONDFAIRY, target: characters.TITANIA },
    { source: characters.SECONDFAIRY, target: characters.FIRSTFAIRY },

    { source: characters.QUINCE, target: characters.BOTTOM },
    { source: characters.QUINCE, target: characters.FLUTE },
    { source: characters.QUINCE, target: characters.STARVELING },
    { source: characters.QUINCE, target: characters.SNOUT },
    { source: characters.QUINCE, target: characters.SNUG },
    { source: characters.QUINCE, target: characters.THESEUS },
    { source: characters.QUINCE, target: characters.HIPPOLYTA },
    { source: characters.QUINCE, target: characters.LYSANDER },
    { source: characters.QUINCE, target: characters.HELENA },
    { source: characters.QUINCE, target: characters.HERMIA },
    { source: characters.QUINCE, target: characters.DEMETRIUS },

    { source: characters.LYSANDER, target: characters.DEMETRIUS },
    { source: characters.LYSANDER, target: characters.THESEUS },
    { source: characters.LYSANDER, target: characters.HERMIA },
    { source: characters.LYSANDER, target: characters.HELENA },
    { source: characters.LYSANDER, target: characters.STARVELING },

    { source: characters.HELENA, target: characters.HERMIA },
    { source: characters.HELENA, target: characters.DEMETRIUS },
    { source: characters.HELENA, target: characters.LYSANDER },

    { source: characters.PUCK, target: characters.OBERON },
    { source: characters.PUCK, target: characters.BOTTOM },
    { source: characters.PUCK, target: characters.LYSANDER },
    { source: characters.PUCK, target: characters.DEMETRIUS },
    { source: characters.PUCK, target: characters.FLUTE },
    { source: characters.PUCK, target: characters.QUINCE },
    { source: characters.PUCK, target: characters.SNOUT },
    { source: characters.PUCK, target: characters.SNUG },
    { source: characters.PUCK, target: characters.STARVELING },
    { source: characters.PUCK, target: characters.FAIRY },
    
    { source: characters.THESEUS, target: characters.HIPPOLYTA },
    { source: characters.THESEUS, target: characters.PHILOSTRATE },
    { source: characters.THESEUS, target: characters.EGEUS },
    { source: characters.THESEUS, target: characters.HERMIA },
    { source: characters.THESEUS, target: characters.LYSANDER },
    { source: characters.THESEUS, target: characters.DEMETRIUS },
    { source: characters.THESEUS, target: characters.HELENA },
    { source: characters.THESEUS, target: characters.FLUTE },
    { source: characters.THESEUS, target: characters.SNUG },
    { source: characters.THESEUS, target: characters.BOTTOM },

    { source: characters.COBWEB, target: characters.BOTTOM },
    { source: characters.COBWEB, target: characters.TITANIA },

    { source: characters.EGEUS, target: characters.THESEUS },
    { source: characters.EGEUS, target: characters.LYSANDER },
    { source: characters.EGEUS, target: characters.DEMETRIUS },

    { source: characters.SNOUT, target: characters.QUINCE },
    { source: characters.SNOUT, target: characters.BOTTOM},

    { source: characters.OBERON, target: characters.TITANIA },
    { source: characters.OBERON, target: characters.PUCK },
    { source: characters.OBERON, target: characters.DEMETRIUS },
    
    { source: characters.STARVELING, target: characters.BOTTOM },
    { source: characters.STARVELING, target: characters.QUINCE},

    { source: characters.FLUTE, target: characters.QUINCE },
    { source: characters.FLUTE, target: characters.SNUG },

    { source: characters.PHILOSTRATE, target: characters.THESEUS },

    { source: characters.MUSTARDSEED, target: characters.TITANIA },
    { source: characters.MUSTARDSEED, target: characters.BOTTOM },

    { source: characters.BOTTOM, target: characters.FLUTE },
    { source: characters.BOTTOM, target: characters.QUINCE },
    { source: characters.BOTTOM, target: characters.SNOUT },
    { source: characters.BOTTOM, target: characters.SNUG },
    { source: characters.BOTTOM, target: characters.STARVELING },
    { source: characters.BOTTOM, target: characters.TITANIA },
    { source: characters.BOTTOM, target: characters.COBWEB },
    { source: characters.BOTTOM, target: characters.MOTE },
    { source: characters.BOTTOM, target: characters.MUSTARDSEED },
    { source: characters.BOTTOM, target: characters.PEASEBLOSSOM },
    { source: characters.BOTTOM, target: characters.THESEUS },
    { source: characters.BOTTOM, target: characters.DEMETRIUS },

    { source: characters.SNUG, target: characters.FLUTE },
    { source: characters.SNUG, target: characters.QUINCE },
    { source: characters.SNUG, target: characters.SNOUT },
    { source: characters.SNUG, target: characters.STARVELING },
    
    { source: characters.FAIRY, target: characters.PUCK }
  ];
